FROM ghcr.io/puppeteer/puppeteer:latest
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

COPY . .
EXPOSE 3000
CMD ["node", "index.js"]
